version: '3.8'

services:
  app:
    build: .
    container_name: app-container
    ports:
      - "192.168.1.104:8000:8000"
    depends_on:
      - redis
    env_file:
      - ./setting/.env

  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack-server